### ISSUE TITLE
Refresh does not seem to work when editing child partials

### ISSUE THREAD

**Issue by sakamies** [pingyhq/pingy-cli#17]
Not sure if I broke something or if this is a bug. I have ejs templates and scss setup. When I edit an scss or ejs partial that's included in the main files, the browser does no show the changes. The funky part is, that it doesn't even show the changes after a hard reload until I edit the main files.

Steps to reproduce:
- Start a new project
- Make a main.scss file
- Import a something.scss file in main.scss
- Edit something.scss and reload the browser

Same goes for ejs templates.

**Comment by davej** [comment]
I can replicate the issue with EJS `includes`, I'll work on fixing that now.

I can't replicate the issue with *.scss imports though.

Tried the following:

> `main.scss`
```scss
@import '_body';
$heading-color: hotpink;

h1 {
  color: $heading-color;
}
```

> `_body.scss`
```scss
body {
  background: green;
}
```

Whenever I edit `_body.scss` then the browser reloads for me.  Please check for errors in the web browser console and let me know what version of node + OS you are using.
